### PR TITLE
Jaxifying the aligned model

### PR DESCRIPTION
**Pull request by nkhusid**
This is a complete implementation of the jaxified `aligned` and `aligned_marginal` models. All additions and changes to the model are housed within `model.py`. I have also included a notebook, `swsh.ipynb`, to demo the code for the spin-weighted spherical harmonics and (+)/(x) angular factors required for the reflection symmetry constraints of the aligned-spin models. 

All changes to other files in the upstream/jaxify branch have been synced and merged prior to commiting.

### CODE REVIEW

**Comment by maxisi** [comment]
Look good, thanks Nicole! This has been merged.

Quick question, though: is there a reason to default to `cosi_min/max` to `-0.99/0.99` rather than `-1/1`?

**Comment by nkhusid** [comment]
Thanks, Max! 

Yeah, these defaults are to avoid `nan` from singular behavior in the SWSH calculations, since the formula depends on trig functions like $\cot(\iota/2)$--see `cot_th_2()` in `sYlm()`.

**Comment by maxisi** [comment]
I see, okay! Another question, in your example notebook, why aren't these ratios exactly `1`:

```
JAX (+) angular factor : hardcoded (+) angular factor = 0.997840404510498
JAX (x) angular factor : hardcoded (x) angular factors = 0.9978403449058533
```

**Comment by nkhusid** [comment]
I think this can be chalked up to a couple of things:

1) `jsp.scipy.special.factorial()` does not return integers but rather floats with some non-zero decimals several places out, this could slightly affect some of the subsequent SWSH calculations.

2) The normalization factor I use, $\sqrt{1/C}$ where I have $C = 0.159$,  seems to vary a bit depending on the indices of the SWSH. $C$ itself varies by $\pm 0.005$. I think this could be an artifact of the above point (1), or of slight variations in the `trapz` calculation of the normalization factor.

**Comment by maxisi** [comment]
I see. Would you be able to track this down exactly? Maybe by checking what happens if you increase the resolution of the $C$ integration? Just to make sure we understand what's going on (no rush)

**Comment by nkhusid** [comment]
So I've played around with it, and the best I can do is get the ratios up to about 0.9986. I think this comes down to the fact that when I integrate to get the noramlization factor, I can't extend the bounds of the integration out to -1 and 1 in $\cos\iota$ without getting nans, as per the above discussion. I've tried varying the resolution of the integration, as well as the closeness of the magnitudes of the integration bounds to unity, and the best I get is:
```
JAX (+) angular factor : hardcoded (+) angular factor = [0.99860257]
JAX (x) angular factor : hardcoded (x) angular factor = [0.99860257]
Percent error compared to hardcoded (+) angular factor = 0.139742%
Percent error compared to hardcoded (x) angular factor = 0.139743%
```

**Pull request merged**
