### PR TITLE
Restore sampling from prior.

### PR DESCRIPTION
**Pull request by maxisi**
Restore option to produce samples from the prior. This requires special handling of variables with the improper `Flat` PyMC prior.

### CODE REVIEW

**Comment by farr** [comment]
Interesting---it looks like you've just replaced the flat prior with a U(-500*A_scale, 500*A_scale) in all cases?  This isn't isotropic (I'm sure you know this), but maybe at 500*A_scale it doesn't matter much since the data will, assuming A_scale is set in a reasonable way, truncate the posterior *long* before you get to such large amplitudes.  Are you sure you want to do this, though?  Have you checked that the sampling goes through OK?

**Comment by maxisi** [comment]
@farr my hope was that `500 A_scale` was big enough, but it seems `Flat` just doesn't work like `Uniform` so this didn't work. In the last commit, I just went back to a Gaussian prior on the quadratures and added a Jacobian—this seems to work just fine. Check it out.

**Comment by farr** [comment]
As I see what you've done, by default the prior is improper, right?  (There's no limit on the amplitude---if `flat_A`---or on the quadratures imposed by the prior.). That means prior sampling is not going to work, right?  (The sampler will diverge to infinity.)

What if we put a (very, very weak) Gaussian prior on the amplitude?  Something like `pm.Potential(-0.5*A*A/(100*A_scale*A_scale))` (that is, a Gaussian with width 10*A_scale).  That so close to flat for small `A` that it doesn't really change the interpretation of the s.d. ratio or anything, but it will make the prior sampling proper.

**Comment by maxisi** [comment]
Right, it wasn’t meant to work for flat_A just gaussian quadratures. but
yeah I like your suggestion of a very mild prior on A

**Comment by farr** [comment]
Yeah, should we put it in even for the `--flat-A` option, just so everything is proper?

**Comment by maxisi** [comment]
I think we should. I can add it tomorrow

**Pull request merged**
