### PR TITLE
Merge PyMC into main

### PR DESCRIPTION
**Pull request by maxisi**
I believe we are ready to make the jump to PyMC. @Potatoasad would this be okay with you or would you like some more time? We can keep a tag with the PyStan code if that's helpful.

### CODE REVIEW

**Comment by Potatoasad** [comment]
Sounds great. Making the jump is completely fine with me!

**Comment by maxisi** [comment]
Cool. Do you want me to try to port your charged model or you got it?

**Comment by Potatoasad** [comment]
No worries, I've got it, I can port it. Unless you want it done on a tight timeline.

**Comment by maxisi** [comment]
@farr I'm gonna go ahead and merge this if that's okay with you

**Comment by maxisi** [comment]
should check with @HarrisonS-Phys too, any objections?

**Comment by farr** [comment]
Yeah, fine by me to merge it.

Will

**Comment by HarrisonS-Phys** [comment]
Looks good to me, let's merge it.

Harrison

**Comment by maxisi** [comment]
Merging this at the request now of @HarrisonS-Phys (@farr, we can still consider NumPyro whenever)

**Pull request merged**
